export const types = {
  SHOW_TOAST: "SHOW_TOAST",
  SHOW_LOADER: "SHOW_LOADER",
  HIDE_LOADER: "HIDE_LOADER",
  SHOW_SIDEBAR_LOADER: "SHOW_SIDEBAR_LOADER",
  HIDE_SIDEBAR_LOADER: "HIDE_SIDEBAR_LOADER",
  UPDATE_UPLOAD_PROGRESS: "UPDATE_UPLOAD_PROGRESS",
  LOCATION_AUTOCOMPLETE: "LOCATION_AUTOCOMPLETE",
  JOB_SEARCH: "JOB_SEARCH",
  POPULAR_JOB_SEARCHES: "POPULAR_JOB_SEARCHES",
};
